### ISSUE TITLE
esprint fails on linux

### ISSUE THREAD

**Issue by Toxicable** [pinterest/esprint#108]
I installed esprint with yarn set my config
```
{
  "paths": [
    "**/*.ts"
  ],
  "ignored": [
    "schematics/*",
    "node_modules/*",
    "coverage/*",
    "**/dist/*",
    "bazel-out/*",
    "external/*",
    "deployments/*"
  ],
  "port": 5001
}

```
and ran `esprint` and got this error:
```
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
```

node: `10.16.3`
yarn: `1.17.3`

**Comment by christianvuerings** [comment]
@Toxicable could you provide a bit more information? What version of esprint are you using and do you have a couple of sample files where it's failing on?

**Comment by Toxicable** [comment]
@christianvuerings esprint `0.5.0`
I don't believe it gets to the point where it's reading files since it cant connect to the server.
However the files we intend to lint are typescript files so `.ts` which we currently lint with eslint directly.

**Comment by christianvuerings** [comment]
@Toxicable Thank you for confirming. We've started to see issues with Node.js versions >8.

Would you be able to try out:
 - Running esprint with Node.js 8
 - Running `8e3f864698b7f709` (latest commit on master): this should fix the issue on newer Node.js versions.

If you confirm it's working on a newer commit, we'll put out a formal release asap.

**Comment by Toxicable** [comment]
That appears to be working now.


However im now running in some other issues, with the above config and installed with `"esprint": "github:pinterest/esprint#8e3f864698b7f709",`

>node ./node_modules/esprint/build/cli.js

returns no output

>node ./node_modules/esprint/build/cli.js check

throws these errors, where as running under native eslint it works fine.
I do have these eslint plugins installs in my project.
```
Error: Failed to load plugin @typescript-eslint: Cannot find module 'eslint-plugin-@typescript-eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Plugins.load (/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config/plugins.js:106:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config/plugins.js:166:21)
    at loadFromDisk (/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config/config-file.js:501:35)
    at Object.load (/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config/config-file.js:559:20)
    at Config.getLocalConfigHierarchy (/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config.js:286:21)
/home/f.wiles/workspace/WORKSPACENAME/node_modules/esprint/node_modules/eslint/lib/config/plugins.js:116
                    throw missingPluginErr;
```

**Comment by caitlinard** [comment]
Hey there, I am running into a similar issue as what is stated in the most recent comment running version 0.6.0
When running esprint on my project:

> esprint
returns no output

> esprint check
Throws errors: `Error: Failed to load plugin babel: Cannot find module 'eslint-plugin-babel'`

**Comment by christianvuerings** [comment]
Please try this again with the latest version of eslint
