### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 75

### ISSUE THREAD

**Issue by caleb15** [pinterest/esprint#123]
```
(fifteen5) > yarn run esprint                                                                  ~/Documents/fifteen5(dev✗)
yarn run v1.22.4
$ /home/caleb/Documents/fifteen5/node_modules/.bin/esprint
Rule | Time (ms) | Relative
:----|----------:|--------:
/home/caleb/Documents/fifteen5/node_modules/esprint/node_modules/yargs/yargs.js:1193
      else throw err
           ^

SyntaxError: Unexpected token } in JSON at position 75
    at JSON.parse (<anonymous>)
    at getEsprintOptions (/home/caleb/Documents/fifteen5/node_modules/esprint/build/cli.js:32:21)
    at Object.handler (/home/caleb/Documents/fifteen5/node_modules/esprint/build/cli.js:73:19)
    at Object.runCommand (/home/caleb/Documents/fifteen5/node_modules/esprint/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/caleb/Documents/fifteen5/node_modules/esprint/node_modules/yargs/yargs.js:1133:35)
    at Object.get [as argv] (/home/caleb/Documents/fifteen5/node_modules/esprint/node_modules/yargs/yargs.js:1033:21)
    at Object.<anonymous> (/home/caleb/Documents/fifteen5/node_modules/esprint/build/cli.js:80:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(fifteen5) > node --version                                                                    ~/Documents/fifteen5(dev✗)
'Tipz:' nodejs --version
v12.18.1
```

The error also happened with `yarn run esprint check`

esprint version 0.7.0
OS: ubuntu 18

.esprintrc: (located in root of repo)
```json
{
  "paths": ["ff/static/modules"],
  "ignored": ["**/node_modules/**/*"],
}
```

**Comment by christianvuerings** [comment]
@caleb15 which Node.js version are you using? Could you try installing Node.js >= 12 and running the commands again?

**Comment by caleb15** [comment]
@christianvuerings the node version is listed above.

```
'Tipz:' nodejs --version
v12.18.1
```

**Comment by christianvuerings** [comment]
Closing this issue since we are not able to repro. @caleb15 feel free to re-open / open a new issue with a repro case.
