### ISSUE TITLE
Eslint V8 not compatible

### ISSUE THREAD

**Issue by LegendSebastianoL** [pinterest/esprint#154]
I just tried to upgrade Eslint from V7 to V8 and Esprint stopped working.
Any hint on why is that?

Our command is `"lint:js": "esprint check",` and dependencies:

```
    "eslint": "^8.0.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-nuxt": "^2.0.0",
```

It's a Nuxt.js project.

esprint config as follow:

```
{
  "paths": ["**/*.vue", "**/*.js"],
  "ignored": ["**/node_modules/**/*"],
  "port": 5004
}
```

The error I have on running the lint is:

```
> esprint check

esprint check

Runs eslint in parallel with no background server

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/glob-util' is not defined by "exports" in /private/var/www/html/my_project/node_modules/eslint/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:437:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/private/var/www/html/my_project/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:43:34)
    at Module._compile (internal/modules/cjs/loader.js:1068:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by LegendSebastiano-L** [comment]
closing as we don't use it anymore.
