### ISSUE TITLE
Tests sometimes fail due to ECONNREFUSED

### ISSUE THREAD

**Issue by arthuralee** [pinterest/esprint#56]
Tests sometimes fail due to ECONNREFUSED. Need to debug the flakiness

**Comment by milesj** [comment]
Alongside ECONNREFUSED, I've also received "(node:24545) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: listen EACCES 0.0.0.0:<PORT>" errors.

**Comment by hoschi** [comment]
I get this and ECONNRESET:
```
yode > lsof -i TCP:9009
yode > esprint
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
yode > esprint
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:9009
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
yode > esprint
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:9009
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
yode > esprint
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
yode > esprint
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
```

Project url: https://github.com/hoschi/yode
`.esprintrc`:
```json
{
  "paths": [
    "packages/core/src/**/*.js"
  ],
  "ignored": [
    "**/node_modules/**/*",
    "**/build/**",
    "**/bundle/**",
    "**/reports/**"
  ],
  "port":9009
}
```

node version: v8.9.1

**Comment by hoschi** [comment]
btw I'm on Linux, colleague with Mac has no problem

**Comment by roopakv** [comment]
Same issue on mac and v8.9.1

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
[Roopaks-MacBook-Pro spoke (master)]$ npx esprint
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 127.0.0.1:5004
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[Roopaks-MacBook-Pro spoke (master)]$ npx esprint --workers=2
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNRESET 127.0.0.1:5004
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[Roopaks-MacBook-Pro spoke (master)]$ npx esprint --workers=1
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
```

**Comment by christianvuerings** [comment]
Since we moved to jayson, I no longer see this issue
