### ISSUE TITLE
Unit tests don't pass on Linux

### ISSUE THREAD

**Issue by kaiyoma** [pinterest/esprint#93]
After cloning and running `yarn install`, I tried running the tests and about half of them fail:

```
> yarn run test
yarn run v1.16.0
$ yarn run build
$ rm -rf build && mkdir build && babel src --out-dir build
src/Client.js -> build/Client.js
src/LintRunner.js -> build/LintRunner.js
src/LintWorker.js -> build/LintWorker.js
src/Server.js -> build/Server.js
src/cli.js -> build/cli.js
src/cliUtils.js -> build/cliUtils.js
src/commands/check.js -> build/commands/check.js
src/commands/connect.js -> build/commands/connect.js
src/commands/index.js -> build/commands/index.js
src/commands/stop.js -> build/commands/stop.js
src/startServer.js -> build/startServer.js
src/util.js -> build/util.js
$ jest tests --runInBand
 FAIL  tests/file-deletion/__tests__/file-deletion.test.js
  ● Properly updates the cache upon deleting a file

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      at Object.<anonymous> (tests/file-deletion/__tests__/file-deletion.test.js:36:25)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

 FAIL  tests/failure/__tests__/failure.test.js
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      at Object.<anonymous> (tests/failure/__tests__/failure.test.js:26:25)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

 FAIL  tests/warning/__tests__/warning.test.js
  ● Properly lints and returns errors with server

    expect(received).toEqual(expected)

    Expected value to equal:
      StringContaining "warning  Unexpected var, use let or const instead  no-var"
    Received:
      ""

      at Object.<anonymous> (tests/warning/__tests__/warning.test.js:27:37)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

 FAIL  tests/subfolders/__tests__/subfolders.test.js
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      at Object.<anonymous> (tests/subfolders/__tests__/subfolders.test.js:26:25)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

 FAIL  tests/suppress-warnings/__tests__/suppress-warnings.test.js
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      at Object.<anonymous> (tests/suppress-warnings/__tests__/suppress-warnings.test.js:19:20)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

 FAIL  tests/fail-on-warning/__tests__/fail-on-warning.test.js
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      at Object.<anonymous> (tests/fail-on-warning/__tests__/fail-on-warning.test.js:17:25)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

 FAIL  tests/success/__tests__/success.test.js
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      at Object.<anonymous> (tests/success/__tests__/success.test.js:26:20)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

 FAIL  tests/stop/__tests__/stop.test.js
  ● Server is properly killed after the stop command

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

      at Object.<anonymous> (tests/stop/__tests__/stop.test.js:25:20)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

Unable to find `.esprintrc` file. Exiting...
 PASS  tests/noconfig/__tests__/noconfig.test.js

Test Suites: 8 failed, 1 passed, 9 total
Tests:       8 failed, 7 passed, 15 total
Snapshots:   0 total
Time:        17.438s
Ran all test suites matching "tests".
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fvgs** [comment]
Hey @kaiyoma, what version of Node are you running?

`yarn run test` currently results in some tests failing when run under Node v10+ due to an outdated sub-dependency (`weak`).

This is something I plan to address along with other outdated dependencies in an upcoming PR.

In the meantime, `yarn run test` should pass if run with Node 9. I'm not aware of any Linux-specific issue. But thanks for reporting and feel free to followup if you find there is an issue other than with the Node version.

**Comment by kaiyoma** [comment]
We run Node 10.16 in our project. I've also encountered test failures on Windows, so you're probably right that nothing here is specific to Linux.

It would be really great if you could address outdated dependencies. I filed https://github.com/pinterest/esprint/issues/92 yesterday and while working on https://github.com/pinterest/esprint/pull/94 I noticed that a lot of dependencies are out of date. Up until you released the new version the other day, my team was maintaining a local fork of the project to fix all these problems, but clearly it would be much better if all these improvements went into mainline.

We find esprint really useful, but the project feels a bit dilapidated at the moment and could definitely use some love and attention to bring it into 2019. Let me know if you need any more help/info.

Off the top of my head:

- Unit tests fail on most/all operating systems
- Dependencies are very outdated
- `yarn audit` reports security vulnerabilities
- Travis builds are failing
- Lots of PRs are stuck in limbo

**Comment by christianvuerings** [comment]
We upgraded all our dependencies and validated the tests now pass on Ubuntu and MacOS. Please retry on the latest version of esprint.

**Comment by kaiyoma** [comment]
Passing on Linux, but still failing pretty badly on Windows:

```
yarn run v1.22.5
$ yarn run build
$ rm -rf build && mkdir build && babel src --out-dir build
Successfully compiled 12 files with Babel (1481ms).
$ jest tests --runInBand
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/file-deletion/__tests__/file-deletion.test.js (10.14 s)
  ● Properly updates the cache upon deleting a file

    TypeError: Cannot read property 'stdout' of undefined

      40 |   const newResults = runEsprint(path.join(__dirname, '..'));
      41 |   const newExpectedResults = expect.stringContaining('');
    > 42 |   expect(newResults.error.stdout.toString()).toEqual(newExpectedResults);
         |                           ^
      43 | });

      at Object.<anonymous> (tests/file-deletion/__tests__/file-deletion.test.js:42:27)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/fix/__tests__/fix.test.js (7.275 s)
  ● Fixes lint errors with server

    expect(received).toBeDefined()

    Received: undefined

      32 |   expect(results.error).toBeUndefined();
      33 |   expect(fixtureContents).not.toEqual(fs.readFileSync(fixture, utf8));
    > 34 |   expect(getPid()).toBeDefined();
         |                    ^
      35 | });
      36 |
      37 | test('Fixes lint errors without server', () => {

      at Object.<anonymous> (tests/fix/__tests__/fix.test.js:34:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/failure/__tests__/failure.test.js (6.24 s)
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Received: undefined

      26 |   expect(results.error).toBeDefined();
      27 |   expect(results.error.stdout.toString()).toEqual(expectedError);
    > 28 |   expect(getPid()).toBeDefined();
         |                    ^
      29 | });
      30 |
      31 | test('Properly lints and returns errors without server', () => {

      at Object.<anonymous> (tests/failure/__tests__/failure.test.js:28:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/warning/__tests__/warning.test.js (6.268 s)
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Received: undefined

      26 |   expect(results.error).toBeUndefined();
      27 |   expect(results.stdout.toString()).toEqual(expectedError);
    > 28 |   expect(getPid()).toBeDefined();
         |                    ^
      29 | });
      30 |
      31 | test('Properly lints and returns errors without server', () => {

      at Object.<anonymous> (tests/warning/__tests__/warning.test.js:28:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/subfolders/__tests__/subfolders.test.js (6.403 s)
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Received: undefined

      26 |   expect(results.error).toBeDefined();
      27 |   expect(results.error.stdout.toString()).toEqual(expectedError);
    > 28 |   expect(getPid()).toBeDefined();
         |                    ^
      29 | });
      30 |
      31 | test('Properly lints and returns errors without server', () => {

      at Object.<anonymous> (tests/subfolders/__tests__/subfolders.test.js:28:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/suppress-warnings/__tests__/suppress-warnings.test.js (6.195 s)
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Received: undefined

      17 |   expect(results.error).toBeUndefined();
      18 |   expect(results.stdout.toString()).not.toEqual(unexpectedError);
    > 19 |   expect(getPid()).toBeDefined();
         |                    ^
      20 | });
      21 |
      22 | test('Properly lints and returns errors without server', () => {

      at Object.<anonymous> (tests/suppress-warnings/__tests__/suppress-warnings.test.js:19:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/fail-on-warning/__tests__/fail-on-warning.test.js (6.549 s)
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Received: undefined

      17 |   expect(results.error).toBeDefined();
      18 |   expect(results.error.stdout.toString()).toEqual(expectedError);
    > 19 |   expect(getPid()).toBeDefined();
         |                    ^
      20 | });
      21 |
      22 | test('Properly lints and returns errors without server', () => {

      at Object.<anonymous> (tests/fail-on-warning/__tests__/fail-on-warning.test.js:19:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/ignored/__tests__/ignored.test.js
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Received: undefined

      24 |   const results = runEsprint(path.join(__dirname, '..'));
      25 |   expect(results.error).not.toBeDefined();
    > 26 |   expect(getPid()).toBeDefined();
         |                    ^
      27 | });
      28 |
      29 | test('Properly lints and returns errors without server', () => {

      at Object.<anonymous> (tests/ignored/__tests__/ignored.test.js:26:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/success/__tests__/success.test.js (6.108 s)
  ● Properly lints and returns errors with server

    expect(received).toBeDefined()

    Received: undefined

      24 |   const results = runEsprint(path.join(__dirname, '..'));
      25 |   expect(results.error).toBeUndefined();
    > 26 |   expect(getPid()).toBeDefined();
         |                    ^
      27 | });
      28 |
      29 | test('Properly lints and returns errors without server', () => {

      at Object.<anonymous> (tests/success/__tests__/success.test.js:26:20)

'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
'lsof' is not recognized as an internal or external command,
operable program or batch file.
 FAIL  tests/stop/__tests__/stop.test.js
  ● Server is properly killed after the stop command

    expect(received).toBeDefined()

    Received: undefined

      23 | test('Server is properly killed after the stop command', () => {
      24 |   runEsprint(path.join(__dirname, '..'));
    > 25 |   expect(getPid()).toBeDefined();
         |                    ^
      26 |   runEsprint(path.join(__dirname, '..'), 'stop');
      27 |   expect(getPid()).toBeUndefined();
      28 | });

      at Object.<anonymous> (tests/stop/__tests__/stop.test.js:25:20)


 RUNS  tests/noconfig/__tests__/noconfig.test.js
```

(the tests seem to hang at this point)
