### ISSUE TITLE
Travis builds aren't working

### ISSUE THREAD

**Issue by kaiyoma** [pinterest/esprint#95]
Example:

https://travis-ci.org/pinterest/esprint/builds/567062990?utm_source=github_status&utm_medium=notification

```
$ yarn
/home/travis/.nvm/versions/node/v4.9.1/lib/node_modules/yarn/lib/cli.js:46083
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v4.9.1/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by christianvuerings** [comment]
We are now using GitHub workflows instead
